name: demo 2
on:
  push:
    branches: main

jobs:
  say hi:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Print Hi
      run: echo "Hi There"
  
