name: Check for SOQL in targeted Apex files

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  check-soql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed TA_* and *Handler.cls files
        id: changes
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/TA_*.cls
            **/*Handler.cls

      - name: Scan selected Apex files for SOQL (static + dynamic)
        if: steps.changes.outputs.all_changed_files != ''
        run: |
          echo "Scanning matched Apex files for SOQL..."

          STATIC_SOQL="SELECT[[:space:]].*FROM"
          DYNAMIC_SOQL="['\"]SELECT[[:space:]].*FROM"
          CONCAT_SOQL="SELECT[[:space:]].*['\"+]+.*FROM"

          for file in ${{ steps.changes.outputs.all_changed_files }}; do
            
            # Double check filename rule (safety net)
            filename=$(basename "$file")
            if [[ ! "$filename" =~ ^TA_.*\.cls$ && ! "$filename" =~ .*Handler\.cls$ ]]; then
              echo "Skipping $file (does not match TA_* or *Handler)"
              continue
            fi

            echo "Checking $file"

            if grep -qiE "$STATIC_SOQL" "$file"; then
              echo "::error file=$file::Found static SOQL SELECT ... FROM"
              exit 1
            fi

            if grep -qiE "$DYNAMIC_SOQL" "$file"; then
              echo "::error file=$file::Found dynamic SOQL inside string literal"
              exit 1
            fi

            if grep -qiE "$CONCAT_SOQL" "$file"; then
              echo "::error file=$file::Found potential dynamic SOQL via string concatenation"
              exit 1
            fi

            echo "✅ $file is clean"
          done

          echo "✅ No forbidden SOQL found in TA_* or *Handler Apex classes"
